### PR TITLE
Issue #77: Add search autosuggestion to Magento

### LINKED ISSUE #77: Quicksearch is broken in the sample-project in the dev-VM
In a local sample-project installation with the shared-fixture sample data the search works.  
However, in the dev-vm it does not work, see attached screenshot.

broken-quicksearch

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**
Closes #77.

### CODE REVIEW

File: src/magento-themes/magento-sample-theme/skin/frontend/lizardsandpumpkins/default/js/modules/header.js [hunk 1]
```diff
@@ -72,23 +71,114 @@
...
+        xmlhttp.send();
+    }
+
+    function isJson(string) {
+        try {
+            JSON.parse(string);
+        } catch (e) {
+            return false;
+        }
+        return true;
```
Comment (Vinai) [inline src/magento-themes/magento-sample-theme/skin/frontend/lizardsandpumpkins/default/js/modules/header.js]: Logically it would be nice to have the `return true;` in the `try{}` block.

Comment (tim-bezhashvyly) [inline src/magento-themes/magento-sample-theme/skin/frontend/lizardsandpumpkins/default/js/modules/header.js]: Done.

**Comment by tim-bezhashvyly** [comment]
Ready for next review.
